feat: implement new coinomics logic
haqq-network/haqq pull request #260
Opened 2023-11-22 17:01 UTC by kioqq

2023-11-23 08:10 UTC, onsails requested changes

2023-11-23 08:10 UTC, onsails commented on .env
remove this

2023-11-23 08:10 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +	yearInMillis, _ := sdk.NewDecFromStr("31536000000")
consider leap years

2023-12-19 18:47 UTC, onsails approved these changes

2023-12-19 18:48 UTC, VorobevSA approved these changes

2023-12-19 18:51 UTC, merged