fix(docs): token description updated
haqq-network/haqq pull request #63
Opened 2022-09-07 15:55 UTC by PastaHash

Closes: #62 

## Description

- token description in basics section updated
- link to islamiccoin website added

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-09-08 17:56 UTC, onsails commented on docs/basics/tokens.md
> +[Islamic Coin](https://islamiccoin.net) (ISLM) is a native currency of Haqq
dot

2022-09-08 17:56 UTC, onsails requested changes

2022-09-08 17:56 UTC, onsails commented on docs/basics/tokens.md
>  Accounts can own SDK coins in their balance, which are used for operations with other Cosmos modules and transactions. Examples of these are using the coins for staking, IBC transfers, governance dep
dot

2022-09-09 15:14 UTC, PastaHash commented on docs/basics/tokens.md
> +[Islamic Coin](https://islamiccoin.net) (ISLM) is a native currency of Haqq
fixed

2022-09-09 15:14 UTC, PastaHash commented on docs/basics/tokens.md
>  Accounts can own SDK coins in their balance, which are used for operations with other Cosmos modules and transactions. Examples of these are using the coins for staking, IBC transfers, governance dep
fixed

2022-09-14 11:28 UTC, onsails approved these changes

2022-09-14 13:32 UTC, kioqq approved these changes

2022-09-14 13:53 UTC, merged