[WIP] Coinomics
haqq-network/haqq pull request #87
Opened 2022-10-05 10:35 UTC by kioqq

Closes: #40

2022-11-25 09:04 UTC, Yurist-85 approved these changes

2022-11-28 13:08 UTC, onsails requested changes

2022-11-28 13:08 UTC, onsails commented on app/test_helpers.go
> +	mintAmount := sdk.TokensFromConsensusPower(20_000_000_000, sdk.DefaultPowerReduction)
Let's move it to constant PremintAmount so that contributors won't be confused of this number origin

2022-11-28 13:08 UTC, onsails commented on proto/haqq/coinomics/v1/genesis.proto
> +  cosmos.base.v1beta1.Coin era_target_supply = 6 [
era_closing_supply

2022-11-28 13:08 UTC, onsails commented on proto/haqq/coinomics/v1/genesis.proto
> +  cosmos.base.v1beta1.Coin target_total_supply = 7 [
max_supply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/client/cli/query.go
> +		Use:   "era-target-supply",
era_closing_supply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/client/cli/query.go
> +		Use:   "total-target-supply",
max_supply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/genesis.go
> +		params.BlocksPerEra = 17280 // 60 days full cycle
// 60 days until max supply minted

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/abci.go
> +		nextEraTargetSupply := currentTotalSupply.AddAmount(nextEraTargetMint.Amount)
nextEraClosingSupply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +	// Allocate first part of coins to EvergreenDAO
remove this

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +	staking := k.bankKeeper.GetAllBalances(ctx, coinomicsModuleAddr)
remove this since it's already known few lines before

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/grpc_query_test.go
> +// func (suite *KeeperTestSuite) TestEpochMintProvision() {
why is this commented?

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +		eraPeriod := uint64(2)
// 2 years

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +		calc_part1 := (sdk.OneDec().Sub(eraCoef)).Mul(totalMintNeeded.Amount.ToDec())
num

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +		calc_part2 := sdk.OneDec().Sub(eraCoef.Power(100 / eraPeriod))
den

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/inflation.go
> +		targetTotalSupply := k.GetTargetTotalSupply(ctx)
maxSupply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/integration_test.go
> +				start_expectedSupplyBigInt, _ := big.NewInt(0).SetString("20000000000000000000000000000", 0)
`big.newInt(20 * 10^9).Mul(10^18)` or smth like this

2022-11-28 13:08 UTC, onsails commented on x/coinomics/keeper/integration_test.go
> +					start_expectedSupplyBigInt, _ := big.NewInt(0).SetString("20000000000000000000000000000", 0)
same as in prev case

2022-11-28 13:08 UTC, onsails commented on x/coinomics/types/genesis.go
> +	targetSupply := sdk.NewIntWithDecimal(100_000_000_000, 18)
maxSupply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/types/genesis.go
> +		EraTargetSupply:   sdk.NewCoin(params.MintDenom, sdk.NewInt(0)),
EraClosingSupply

2022-11-28 13:08 UTC, onsails commented on x/coinomics/types/genesis.go
> +		TargetTotalSupply: sdk.NewCoin(params.MintDenom, targetSupply),
MaxSupply

2022-12-05 11:00 UTC, onsails approved these changes

2022-12-05 11:00 UTC, merged

2023-02-20 06:44 UTC, C0834anDra reviewed
Ok

2023-07-27 07:56 UTC, kormialis commented
nice

2023-07-30 17:48 UTC, Hurraira8886 commented
Awesome

2023-08-01 12:28 UTC, annhien1235 commented
nice

2023-08-01 20:23 UTC, Faizankh53 commented
Great project

2023-08-02 11:32 UTC, Saurov0000 commented
Good performance

2023-08-10 21:32 UTC, 1diond commented
Lfg 🫶

2023-08-15 11:20 UTC, al-connected commented
great indeed

2023-08-18 22:21 UTC, Anitachi commented
great and exciting project to be part of it

2023-08-21 05:35 UTC, Sekani179 commented
How do I get the validator role??

2023-08-21 10:34 UTC, khumer5540 commented
Ok 👍

2023-08-21 22:56 UTC, aminlucent commented
Excellent project

2023-08-25 16:46 UTC, Atull1234 commented
Wonderful project

2023-08-26 05:28 UTC, Sekani179 commented
🙌Great project 💚🌙